import type { Metadata } from "next";
import "../styles/app.scss";
import fonts from "../styles/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
          <body className={fonts.passionSansPDae.className}>{children}</body>
      </html>
  );
}
